export const countries = [
    { value: 'Afganistan', label: 'Afganistán' },
    { value: 'Albania', label: 'Albania' },
    { value: 'Alemania', label: 'Alemania' },
    { value: 'Andorra', label: 'Andorra' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Antigua_y_Barbuda', label: 'Antigua y Barbuda' },
    { value: 'Arabia_Saudita', label: 'Arabia Saudita' },
    { value: 'Argelia', label: 'Argelia' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Armenia', label: 'Armenia' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Azerbaiyan', label: 'Azerbaiyán' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Barbados', label: 'Barbados' },
    { value: 'Barein', label: 'Baréin' },
    { value: 'Belgica', label: 'Bélgica' },
    { value: 'Belice', label: 'Belice' },
    { value: 'Benin', label: 'Benín' },
    { value: 'Bielorrusia', label: 'Bielorrusia' },
    { value: 'Birmania', label: 'Birmania' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Bosnia_y_Herzegovina', label: 'Bosnia y Herzegovina' },
    { value: 'Botsuana', label: 'Botsuana' },
    { value: 'Brasil', label: 'Brasil' },
    { value: 'Brunei', label: 'Brunéi' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Burkina_Faso', label: 'Burkina Faso' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Butan', label: 'Bután' },
    { value: 'Cabo_Verde', label: 'Cabo Verde' },
    { value: 'Camboya', label: 'Camboya' },
    { value: 'Camerun', label: 'Camerún' },
    { value: 'Canada', label: 'Canadá' },
    { value: 'Catar', label: 'Catar' },
    { value: 'Chad', label: 'Chad' },
    { value: 'Chile', label: 'Chile' },
    { value: 'China', label: 'China' },
    { value: 'Chipre', label: 'Chipre' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Comoras', label: 'Comoras' },
    { value: 'Congo', label: 'Congo' },
    { value: 'Corea_del_Norte', label: 'Corea del Norte' },
    { value: 'Corea_del_Sur', label: 'Corea del Sur' },
    { value: 'Costa_de_Marfil', label: 'Costa de Marfil' },
    { value: 'Costa_Rica', label: 'Costa Rica' },
    { value: 'Croacia', label: 'Croacia' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Dinamarca', label: 'Dinamarca' },
    { value: 'Dominica', label: 'Dominica' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'Egipto', label: 'Egipto' },
    { value: 'El_Salvador', label: 'El Salvador' },
    { value: 'Emiratos_Arabes_Unidos', label: 'Emiratos Árabes Unidos' },
    { value: 'Eritrea', label: 'Eritrea' },
    { value: 'Eslovaquia', label: 'Eslovaquia' },
    { value: 'Eslovenia', label: 'Eslovenia' },
    { value: 'Espana', label: 'España' },
    { value: 'Estados_Unidos', label: 'Estados Unidos' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Etiopia', label: 'Etiopía' },
    { value: 'Filipinas', label: 'Filipinas' },
    { value: 'Finlandia', label: 'Finlandia' },
    { value: 'Fiyi', label: 'Fiyi' },
    { value: 'Francia', label: 'Francia' },
    { value: 'Gabon', label: 'Gabón' },
    { value: 'Gambia', label: 'Gambia' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Granada', label: 'Granada' },
    { value: 'Grecia', label: 'Grecia' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guinea', label: 'Guinea' },
    { value: 'Guinea_ecuatorial', label: 'Guinea Ecuatorial' },
    { value: 'Guinea_Bissau', label: 'Guinea-Bisáu' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Haiti', label: 'Haití' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Hungria', label: 'Hungría' },
    { value: 'India', label: 'India' },
    { value: 'Indonesia', label: 'Indonesia' },
    { value: 'Irak', label: 'Irak' },
    { value: 'Iran', label: 'Irán' },
    { value: 'Irlanda', label: 'Irlanda' },
    { value: 'Islandia', label: 'Islandia' },
    { value: 'Islas_Marshall', label: 'Islas Marshall' },
    { value: 'Islas_Salomon', label: 'Islas Salomón' },
    { value: 'Israel', label: 'Israel' },
    { value: 'Italia', label: 'Italia' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Japon', label: 'Japón' },
    { value: 'Jordania', label: 'Jordania' },
    { value: 'Kazajistan', label: 'Kazajistán' },
    { value: 'Kenia', label: 'Kenia' },
    { value: 'Kirguistan', label: 'Kirguistán' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Kuwait', label: 'Kuwait' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Lesoto', label: 'Lesoto' },
    { value: 'Letonia', label: 'Letonia' },
    { value: 'Libano', label: 'Líbano' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Libia', label: 'Libia' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Lituania', label: 'Lituania' },
    { value: 'Luxemburgo', label: 'Luxemburgo' },
    { value: 'Madagascar', label: 'Madagascar' },
    { value: 'Malasia', label: 'Malasia' },
    { value: 'Malawi', label: 'Malaui' },
    { value: 'Maldivas', label: 'Maldivas' },
    { value: 'Mali', label: 'Malí' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Marruecos', label: 'Marruecos' },
    { value: 'Mauricio', label: 'Mauricio' },
    { value: 'Mauritania', label: 'Mauritania' },
    { value: 'Mexico', label: 'México' },
    { value: 'Micronesia', label: 'Micronesia' },
    { value: 'Moldavia', label: 'Moldavia' },
    { value: 'Monaco', label: 'Mónaco' },
    { value: 'Mongolia', label: 'Mongolia' },
    { value: 'Montenegro', label: 'Montenegro' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Namibia', label: 'Namibia' },
    { value: 'Nauru', label: 'Nauru' },
    { value: 'Nepal', label: 'Nepal' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Niger', label: 'Níger' },
    { value: 'Nigeria', label: 'Nigeria' },
    { value: 'Noruega', label: 'Noruega' },
    { value: 'Nueva_Zelanda', label: 'Nueva Zelanda' },
    { value: 'Oman', label: 'Omán' },
    { value: 'Paises_Bajos', label: 'Países Bajos' },
    { value: 'Pakistan', label: 'Pakistán' },
    { value: 'Palaos', label: 'Palaos' },
    { value: 'Palestina', label: 'Palestina' },
    { value: 'Panama', label: 'Panamá' },
    { value: 'Papua_Nueva_Guinea', label: 'Papúa Nueva Guinea' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Peru', label: 'Perú' },
    { value: 'Polonia', label: 'Polonia' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Reino_Unido', label: 'Reino Unido' },
    { value: 'Republica_Centroafricana', label: 'República Centroafricana' },
    { value: 'Republica_Checa', label: 'República Checa' },
    { value: 'Republica_Democratica_del_Congo', label: 'República Democrática del Congo' },
    { value: 'Republica_Dominicana', label: 'República Dominicana' },
    { value: 'Ruanda', label: 'Ruanda' },
    { value: 'Rumania', label: 'Rumanía' },
    { value: 'Rusia', label: 'Rusia' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'San_Cristobal_y_Nieves', label: 'San Cristóbal y Nieves' },
    { value: 'San_Marino', label: 'San Marino' },
    { value: 'San_Vicente_y_las_Granadinas', label: 'San Vicente y las Granadinas' },
    { value: 'Santa_Lucia', label: 'Santa Lucía' },
    { value: 'Santo_Tome_y_Principe', label: 'Santo Tomé y Príncipe' },
    { value: 'Senegal', label: 'Senegal' },
    { value: 'Serbia', label: 'Serbia' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Sierra_Leona', label: 'Sierra Leona' },
    { value: 'Singapur', label: 'Singapur' },
    { value: 'Siria', label: 'Siria' },
    { value: 'Somalia', label: 'Somalia' },
    { value: 'Sri_Lanka', label: 'Sri Lanka' },
    { value: 'Suazilandia', label: 'Suazilandia' },
    { value: 'Sudafrica', label: 'Sudáfrica' },
    { value: 'Sudan', label: 'Sudán' },
    { value: 'Sudan_del_Sur', label: 'Sudán del Sur' },
    { value: 'Suecia', label: 'Suecia' },
    { value: 'Suiza', label: 'Suiza' },
    { value: 'Surinam', label: 'Surinam' },
    { value: 'Tailandia', label: 'Tailandia' },
    { value: 'Tanzania', label: 'Tanzania' },
    { value: 'Tayikistan', label: 'Tayikistán' },
    { value: 'Timor_Oriental', label: 'Timor Oriental' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Tonga', label: 'Tonga' },
    { value: 'Trinidad_y_Tobago', label: 'Trinidad y Tobago' },
    { value: 'Tunez', label: 'Túnez' },
    { value: 'Turkmenistan', label: 'Turkmenistán' },
    { value: 'Turquia', label: 'Turquía' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Ucrania', label: 'Ucrania' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Uzbekistan', label: 'Uzbekistán' },
    { value: 'Vanuatu', label: 'Vanuatu' },
    { value: 'Vaticano', label: 'Vaticano' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'Yemen', label: 'Yemen' },
    { value: 'Yibuti', label: 'Yibuti' },
    { value: 'Zambia', label: 'Zambia' },
    { value: 'Zimbabue', label: 'Zimbabue' }
  ];

  export const theme = [
    { value: 'Politica', label: 'Política' },
    { value: 'Historica', label: 'Histórica' },
    { value: 'Gastronomica', label: 'Gastronómica' },
    { value: 'Artística', label: 'Cultural' },
    { value: 'Turistica', label: 'Turística' }
  ];