export const countries = [
    { key: 'Afganistan', value: 'Afganistán' },
    { key: 'Albania', value: 'Albania' },
    { key: 'Alemania', value: 'Alemania' },
    { key: 'Andorra', value: 'Andorra' },
    { key: 'Angola', value: 'Angola' },
    { key: 'Antigua_y_Barbuda', value: 'Antigua y Barbuda' },
    { key: 'Arabia_Saudita', value: 'Arabia Saudita' },
    { key: 'Argelia', value: 'Argelia' },
    { key: 'Argentina', value: 'Argentina' },
    { key: 'Armenia', value: 'Armenia' },
    { key: 'Australia', value: 'Australia' },
    { key: 'Austria', value: 'Austria' },
    { key: 'Azerbaiyan', value: 'Azerbaiyán' },
    { key: 'Bahamas', value: 'Bahamas' },
    { key: 'Bangladesh', value: 'Bangladesh' },
    { key: 'Barbados', value: 'Barbados' },
    { key: 'Barein', value: 'Baréin' },
    { key: 'Belgica', value: 'Bélgica' },
    { key: 'Belice', value: 'Belice' },
    { key: 'Benin', value: 'Benín' },
    { key: 'Bielorrusia', value: 'Bielorrusia' },
    { key: 'Birmania', value: 'Birmania' },
    { key: 'Bolivia', value: 'Bolivia' },
    { key: 'Bosnia_y_Herzegovina', value: 'Bosnia y Herzegovina' },
    { key: 'Botsuana', value: 'Botsuana' },
    { key: 'Brasil', value: 'Brasil' },
    { key: 'Brunei', value: 'Brunéi' },
    { key: 'Bulgaria', value: 'Bulgaria' },
    { key: 'Burkina_Faso', value: 'Burkina Faso' },
    { key: 'Burundi', value: 'Burundi' },
    { key: 'Butan', value: 'Bután' },
    { key: 'Cabo_Verde', value: 'Cabo Verde' },
    { key: 'Camboya', value: 'Camboya' },
    { key: 'Camerun', value: 'Camerún' },
    { key: 'Canada', value: 'Canadá' },
    { key: 'Catar', value: 'Catar' },
    { key: 'Chad', value: 'Chad' },
    { key: 'Chile', value: 'Chile' },
    { key: 'China', value: 'China' },
    { key: 'Chipre', value: 'Chipre' },
    { key: 'Colombia', value: 'Colombia' },
    { key: 'Comoras', value: 'Comoras' },
    { key: 'Congo', value: 'Congo' },
    { key: 'Corea_del_Norte', value: 'Corea del Norte' },
    { key: 'Corea_del_Sur', value: 'Corea del Sur' },
    { key: 'Costa_de_Marfil', value: 'Costa de Marfil' },
    { key: 'Costa_Rica', value: 'Costa Rica' },
    { key: 'Croacia', value: 'Croacia' },
    { key: 'Cuba', value: 'Cuba' },
    { key: 'Dinamarca', value: 'Dinamarca' },
    { key: 'Dominica', value: 'Dominica' },
    { key: 'Ecuador', value: 'Ecuador' },
    { key: 'Egipto', value: 'Egipto' },
    { key: 'El_Salvador', value: 'El Salvador' },
    { key: 'Emiratos_Arabes_Unidos', value: 'Emiratos Árabes Unidos' },
    { key: 'Eritrea', value: 'Eritrea' },
    { key: 'Eslovaquia', value: 'Eslovaquia' },
    { key: 'Eslovenia', value: 'Eslovenia' },
    { key: 'Espana', value: 'España' },
    { key: 'Estados_Unidos', value: 'Estados Unidos' },
    { key: 'Estonia', value: 'Estonia' },
    { key: 'Etiopia', value: 'Etiopía' },
    { key: 'Filipinas', value: 'Filipinas' },
    { key: 'Finlandia', value: 'Finlandia' },
    { key: 'Fiyi', value: 'Fiyi' },
    { key: 'Francia', value: 'Francia' },
    { key: 'Gabon', value: 'Gabón' },
    { key: 'Gambia', value: 'Gambia' },
    { key: 'Georgia', value: 'Georgia' },
    { key: 'Ghana', value: 'Ghana' },
    { key: 'Granada', value: 'Granada' },
    { key: 'Grecia', value: 'Grecia' },
    { key: 'Guatemala', value: 'Guatemala' },
    { key: 'Guinea', value: 'Guinea' },
    { key: 'Guinea_ecuatorial', value: 'Guinea Ecuatorial' },
    { key: 'Guinea_Bissau', value: 'Guinea-Bisáu' },
    { key: 'Guyana', value: 'Guyana' },
    { key: 'Haiti', value: 'Haití' },
    { key: 'Honduras', value: 'Honduras' },
    { key: 'Hungria', value: 'Hungría' },
    { key: 'India', value: 'India' },
    { key: 'Indonesia', value: 'Indonesia' },
    { key: 'Irak', value: 'Irak' },
    { key: 'Iran', value: 'Irán' },
    { key: 'Irlanda', value: 'Irlanda' },
    { key: 'Islandia', value: 'Islandia' },
    { key: 'Islas_Marshall', value: 'Islas Marshall' },
    { key: 'Islas_Salomon', value: 'Islas Salomón' },
    { key: 'Israel', value: 'Israel' },
    { key: 'Italia', value: 'Italia' },
    { key: 'Jamaica', value: 'Jamaica' },
    { key: 'Japon', value: 'Japón' },
    { key: 'Jordania', value: 'Jordania' },
    { key: 'Kazajistan', value: 'Kazajistán' },
    { key: 'Kenia', value: 'Kenia' },
    { key: 'Kirguistan', value: 'Kirguistán' },
    { key: 'Kiribati', value: 'Kiribati' },
    { key: 'Kuwait', value: 'Kuwait' },
    { key: 'Laos', value: 'Laos' },
    { key: 'Lesoto', value: 'Lesoto' },
    { key: 'Letonia', value: 'Letonia' },
    { key: 'Libano', value: 'Líbano' },
    { key: 'Liberia', value: 'Liberia' },
    { key: 'Libia', value: 'Libia' },
    { key: 'Liechtenstein', value: 'Liechtenstein' },
    { key: 'Lituania', value: 'Lituania' },
    { key: 'Luxemburgo', value: 'Luxemburgo' },
    { key: 'Madagascar', value: 'Madagascar' },
    { key: 'Malasia', value: 'Malasia' },
    { key: 'Malawi', value: 'Malaui' },
    { key: 'Maldivas', value: 'Maldivas' },
    { key: 'Mali', value: 'Malí' },
    { key: 'Malta', value: 'Malta' },
    { key: 'Marruecos', value: 'Marruecos' },
    { key: 'Mauricio', value: 'Mauricio' },
    { key: 'Mauritania', value: 'Mauritania' },
    { key: 'Mexico', value: 'México' },
    { key: 'Micronesia', value: 'Micronesia' },
    { key: 'Moldavia', value: 'Moldavia' },
    { key: 'Monaco', value: 'Mónaco' },
    { key: 'Mongolia', value: 'Mongolia' },
    { key: 'Montenegro', value: 'Montenegro' },
    { key: 'Mozambique', value: 'Mozambique' },
    { key: 'Namibia', value: 'Namibia' },
    { key: 'Nauru', value: 'Nauru' },
    { key: 'Nepal', value: 'Nepal' },
    { key: 'Nicaragua', value: 'Nicaragua' },
    { key: 'Niger', value: 'Níger' },
    { key: 'Nigeria', value: 'Nigeria' },
    { key: 'Noruega', value: 'Noruega' },
    { key: 'Nueva_Zelanda', value: 'Nueva Zelanda' },
    { key: 'Oman', value: 'Omán' },
    { key: 'Paises_Bajos', value: 'Países Bajos' },
    { key: 'Pakistan', value: 'Pakistán' },
    { key: 'Palaos', value: 'Palaos' },
    { key: 'Palestina', value: 'Palestina' },
    { key: 'Panama', value: 'Panamá' },
    { key: 'Papua_Nueva_Guinea', value: 'Papúa Nueva Guinea' },
    { key: 'Paraguay', value: 'Paraguay' },
    { key: 'Peru', value: 'Perú' },
    { key: 'Polonia', value: 'Polonia' },
    { key: 'Portugal', value: 'Portugal' },
    { key: 'Reino_Unido', value: 'Reino Unido' },
    { key: 'Republica_Centroafricana', value: 'República Centroafricana' },
    { key: 'Republica_Checa', value: 'República Checa' },
    { key: 'Republica_Democratica_del_Congo', value: 'República Democrática del Congo' },
    { key: 'Republica_Dominicana', value: 'República Dominicana' },
    { key: 'Ruanda', value: 'Ruanda' },
    { key: 'Rumania', value: 'Rumanía' },
    { key: 'Rusia', value: 'Rusia' },
    { key: 'Samoa', value: 'Samoa' },
    { key: 'San_Cristobal_y_Nieves', value: 'San Cristóbal y Nieves' },
    { key: 'San_Marino', value: 'San Marino' },
    { key: 'San_Vicente_y_las_Granadinas', value: 'San Vicente y las Granadinas' },
    { key: 'Santa_Lucia', value: 'Santa Lucía' },
    { key: 'Santo_Tome_y_Principe', value: 'Santo Tomé y Príncipe' },
    { key: 'Senegal', value: 'Senegal' },
    { key: 'Serbia', value: 'Serbia' },
    { key: 'Seychelles', value: 'Seychelles' },
    { key: 'Sierra_Leona', value: 'Sierra Leona' },
    { key: 'Singapur', value: 'Singapur' },
    { key: 'Siria', value: 'Siria' },
    { key: 'Somalia', value: 'Somalia' },
    { key: 'Sri_Lanka', value: 'Sri Lanka' },
    { key: 'Suazilandia', value: 'Suazilandia' },
    { key: 'Sudafrica', value: 'Sudáfrica' },
    { key: 'Sudan', value: 'Sudán' },
    { key: 'Sudan_del_Sur', value: 'Sudán del Sur' },
    { key: 'Suecia', value: 'Suecia' },
    { key: 'Suiza', value: 'Suiza' },
    { key: 'Surinam', value: 'Surinam' },
    { key: 'Tailandia', value: 'Tailandia' },
    { key: 'Tanzania', value: 'Tanzania' },
    { key: 'Tayikistan', value: 'Tayikistán' },
    { key: 'Timor_Oriental', value: 'Timor Oriental' },
    { key: 'Togo', value: 'Togo' },
    { key: 'Tonga', value: 'Tonga' },
    { key: 'Trinidad_y_Tobago', value: 'Trinidad y Tobago' },
    { key: 'Tunez', value: 'Túnez' },
    { key: 'Turkmenistan', value: 'Turkmenistán' },
    { key: 'Turquia', value: 'Turquía' },
    { key: 'Tuvalu', value: 'Tuvalu' },
    { key: 'Ucrania', value: 'Ucrania' },
    { key: 'Uganda', value: 'Uganda' },
    { key: 'Uruguay', value: 'Uruguay' },
    { key: 'Uzbekistan', value: 'Uzbekistán' },
    { key: 'Vanuatu', value: 'Vanuatu' },
    { key: 'Vaticano', value: 'Vaticano' },
    { key: 'Venezuela', value: 'Venezuela' },
    { key: 'Vietnam', value: 'Vietnam' },
    { key: 'Yemen', value: 'Yemen' },
    { key: 'Yibuti', value: 'Yibuti' },
    { key: 'Zambia', value: 'Zambia' },
    { key: 'Zimbabue', value: 'Zimbabue' }
  ];

  export const theme = [
    { key: 'Politica', value: 'Política' },
    { key: 'Historica', value: 'Histórica' },
    { key: 'Gastronomica', value: 'Gastronómica' },
    { key: 'Artística', value: 'Cultural' },
    { key: 'Turistica', value: 'Turística' }
  ];